# -*- coding: utf-8 -*-
"""AppLoanApprovalModel

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LtMXkUlf5nvAQ2NNPPOSlF5c3w4K1h8i

#**To Make User Interface (UI) Using Gradio**`
"""

!pip install gradio

import gradio as gr
import pandas as pd
import numpy as np
import joblib

model = joblib.load('/content/drive/MyDrive/LoanApprovalModel/LoanAapprovalTrainedModel.joblib')
ohe = joblib.load('/content/drive/MyDrive/LoanApprovalModel/onehotencoder.joblib')
oe = joblib.load('/content/drive/MyDrive/LoanApprovalModel/ordinalencoder.joblib')
print('1-Model Loaded')

# make function loan approval app
def loan_approval_f(
        Gender, Marital_Status, Education, Employment_Status, Occupation_Type, Residential_Status, City_Town, Loan_Purpose,Loan_Type, Co_Applicant,Loan_History,

        Age, Dependents, no_Served_Loan, Interest_Rate, Annual_Income, Monthly_Expenses, Total_Existing_Loan_Amount, Outstanding_Debt,Loan_Amount_Requested, Loan_Months, ):

    print("Gender  : " , Gender)
    print("2-function fetch the input values")

    Loan_History = 1 if Loan_History == 'Yes' else 0

    # Convert input Ordinal Catogorial Feature Variables "Education" into numbers
    Education_df = [[Education]]
    Education = oe.transform(Education_df)[0][0]

    # convert int float type input values into an array
    int_float_df = [[Age,Dependents,Education,Annual_Income,Monthly_Expenses,no_Served_Loan,Total_Existing_Loan_Amount,Outstanding_Debt,Loan_History,Loan_Amount_Requested,Loan_Months,Interest_Rate]]
    int_float_array = np.array(int_float_df)

    # Covert input Nominal Categorical Feature Variables into an array
    nominal_categorical_df = [[Gender,Marital_Status,Employment_Status,Occupation_Type,Residential_Status,City_Town,Loan_Purpose,Loan_Type,Co_Applicant]]
    nominal_categorical_df=ohe.transform(nominal_categorical_df).toarray()

    # combine all inputs into 1 array
    final_input = np.hstack((int_float_array,nominal_categorical_df))

    # Prediction
    prediction = model.predict(final_input)

    if prediction[0]==1:
          return "Loan Approved"
    else:
         return "Loan not Approved"

iface = gr.Interface(
    fn = loan_approval_f,

    inputs=[

        gr.Dropdown(choices=['Male','Female'],
                      value='',
                     label = 'Gender'),
        gr.Dropdown(choices=['Married','Single','Divorced'],
                      value='',
                     label = 'Marital Status'),
        gr.Dropdown(choices=['High School','Graduate','Postgraduate'],
                      value='',
                     label = 'Education'),
        gr.Dropdown(choices=['Employed', 'Self-Employed','Unemployed'],
                      value='',
                     label = 'Employment Status'),
        gr.Dropdown(choices=['Business','Freelancer','Salaried','Professional'],
                      value='',
                     label = 'Occupation Type'),
        gr.Dropdown(choices=['Own','Rent','Other'],
                      value='',
                     label = 'Residential Status'),
        gr.Dropdown(choices=['Urban','Suburban','Rural'],
                      value='',
                     label = 'Region'),
        gr.Dropdown(choices=['Home','Vehicle','Personal','Education'],
                      value='',
                     label = 'Loan Purpose'),
        gr.Dropdown(choices=['Secured','Unsecured'],
                      value='',
                     label = 'Loan Type'),
        gr.Dropdown(choices=['Yes','No'],
                      value='',
                      label= 'CoApplicant'),
        gr.Dropdown(choices=['Yes','No'],
                      value='',
                      label= 'Loan History'),

        gr.Slider(18,70,step=1,value=1,     label='Age'),
        gr.Slider(0,5,step=1,value=0,       label="Dependent's Persons"),
        gr.Slider(0,2,step=1,value=0,       label='Number of Served Loan'),
        gr.Slider(3.5,15,step=0.1,value=3.5,label='Interest Rate'),
        gr.Number(                          label='Annual Income'),
        gr.Number(                          label='Monthly Expenses'),
        gr.Number(                          label='Total Existing Loan Amount'),
        gr.Number(                          label='Outstanding Debt'),
        gr.Number(                          label='Loan Amount Requested'),
        gr.Number(value=12,                 label='Loan_Months')

        ],

    outputs = gr.Textbox(label = 'Loan Status'),
    title = "Loan Approval Prediction App",
    description = "Enter Loan Application Details to Predict Approval"
)
iface.launch(share=True,debug=True)