# -*- coding: utf-8 -*-
"""LoanApprovalModel

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12z5eGWG36konAWi2W5r2aJW8kBaku8Eo

#**Loan-Approval Prediction Classifier**

**Description of Dataset**

This dataset contains a wealth of information from 52,000 loan applications, offering detailed insights into the factors that influence loan approval decisions. Collected from financial institutions, this data is highly valuable for credit risk analysis, financial modeling, and predictive analytics. The dataset is particularly useful for anyone interested in applying machine learning techniques to real-world financial decision-making scenarios.

Overview:
This dataset provides information about various applicants and the loans they applied for, including their demographic details, income, loan terms, and approval status. By analyzing this data, one can gain an understanding of which factors are most critical for determining the likelihood of loan approval. The dataset can also help in evaluating credit risk and building robust credit scoring systems.
https://www.kaggle.com/datasets/arbaaztamboli/loan-approval-dataset
"""

import pandas as pd
import numpy as np
# Load Dataset from my Google Drive
df = pd.read_csv("/content/drive/MyDrive/LoanApprovalModel/LoanApprovalDataset.csv")
df.head(10)

"""**Data Cleaning**"""

df.columns

df.info()

numeric_col = df.select_dtypes(include=['int','float']).columns
print(numeric_col)

df1 = df[['Existing_Loans', 'Total_Existing_Loan_Amount', 'Outstanding_Debt',
       'Loan_History', 'Loan_Term']]
df1.head(5)

df['Existing_Loans'].value_counts() # no of serving loan

df.rename(columns={'Existing_Loans':'no_Served_Loan'},inplace=True)

# Loan_History: The applicant’s previous loan history (Good/Bad), indicating their repayment reliability.
df['Loan_History'].value_counts()

# Loan_Term: The term of the loan in months.
df['Loan_Term'].value_counts()

df.rename(columns={'Loan_Term':'Loan_Months'}, inplace=True)

df1 = df[['no_Served_Loan', 'Total_Existing_Loan_Amount', 'Outstanding_Debt',
       'Loan_History', 'Loan_Months']]
df1.head(5)

numeric_col = df.select_dtypes(include=['int','float']).columns
print(numeric_col)

# print only the categorial columns from dataset
categorical_col = df.select_dtypes(include=['object','category']).columns
print(categorical_col)

# check the fields of categorial columns one by one and check which columns are unnecessary
df['Gender'].unique()

# delete the unnessary columns
#Credit_Score: The applicant's credit score, reflecting their creditworthiness.
#Bank_Account_History: Applicant’s banking history, showing past transactions and reliability.
#Transaction_Frequency: The frequency of financial transactions in the applicant’s bank account (Low/Medium/High).
#Default_Risk: The risk level of the applicant defaulting on the loan (Low/Medium/High).
df.drop(columns=['Applicant_ID','Credit_Score','Bank_Account_History','Transaction_Frequency','Default_Risk'], inplace = True)

df.info()

# Checking - Is there exists null values in the dataset or not?
df[df.isnull().any(axis=1)]

# Checking the missing data
df.isnull().sum()

# Delete the rows which have any missing value
df.dropna(axis=0,inplace=True)

# Remove spaces in the column names/headings
df.columns = df.columns.str.strip()

# checking the duplicate values
df.duplicated().sum()

df = df.drop_duplicates(keep='first')

# Checking Again  - How many no. of rows and no. of columns
df.shape

"""**EDA - Exploratory Data Analysis**"""

# checking outliers
import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(20,8))
sns.boxplot(data=df)

"""**Observations :**

Annual_Income, Applicant_ID, Existing_Loan_Amount, Outstanding_Debt, and Loan_Amount_Requested show the largest spread, indicating high variability in these features.
Loan_Amount_Requested contains several outliers, while most other variables show few or no noticeable outliers.
Binary/categorical features such as Loan_History, Existing_Loans, Loan_Term, Interest_Rate, Bank_Account_History, Transaction_Frequency, Default_Risk, and Loan_Approval_Status are compressed near zero because they are plotted on the same scale as large numeric features.
"""

# no of people who took loan by gender
gender = df['Gender'].value_counts()
print(gender)
plt.pie(df['Gender'].value_counts(), labels=['Male','Female'], autopct='%1.1f%%')

"""**Observe the pie graph**

The dataset is perfectly balanced by gender, with 26,011 male applicants (50.0%) and 25,989 female applicants (50.0%).
This balanced gender distribution helps reduce gender-related sampling bias, making the dataset suitable for fair model training.
"""

# Observe loan status column as per Gender
df.groupby(['Gender'])['Loan_Approval_Status'].value_counts(normalize=True).unstack().plot(kind='bar')

"""**Observation : Gender has little to no impact on loan approval, as both males and females have nearly identical approval and rejection rates.**"""

# no of people who took loan by age
age = df['Age'].value_counts()
print(age)
plt.figure(figsize=(20,8))
sns.countplot(x='Age', data=df)

"""**Observe the boxplot graph**

The age distribution is highest and relatively uniform between 25 and 49 years, indicating that most applicants belong to the working-age population.
Fewer applicants are below 25 or above 50 years, showing that younger and older age groups are underrepresented in the dataset.
"""

# Observe loan status column
status = df['Loan_Approval_Status'].value_counts()
print(status)
plt.pie(df['Loan_Approval_Status'].value_counts(), labels=['Aproved','Not Approved' ], autopct='%1.1f%%')

"""**observations : The dataset is moderately imbalanced, with 64.2% of loan applications approved and 35.8% not approved.**"""

# no of people who took loan by marital status
gender = df['Marital_Status'].value_counts()
print(gender)
plt.pie(df['Marital_Status'].value_counts(), labels=['Married', 'Single' ,'Divorced'], autopct='%1.1f%%')

# Observe loan status column as per Marital_Status
df.groupby(['Marital_Status'])['Loan_Approval_Status'].value_counts(normalize=True).unstack().plot(kind='bar')

"""**Marital status has minimal impact on loan approval, as divorced, married, and single applicants all show nearly identical approval and rejection rates.**"""

df.select_dtypes(include=['int']).describe()

"""Annual income ranges from 20,009 to 149,998, with a median of 78,839, indicating a wide spread.                                         
Monthly expenses range from 500 to 4,999, with a median of 2,739, showing moderate variability.                                                     
Existing loan amounts vary widely from 0 to 49,999, indicating high variability.
Outstanding debt ranges from 0 to 29,998, with considerable variation across applicants.                                                            
Requested loan amounts range from 5,000 to 44,848, with a median of 21,039, showing moderate dispersion.

"""

int_col = df.select_dtypes(include=['int64']).columns
print(int_col)

numeric_df = df.select_dtypes(include=['int'])
numeric_df.head(5)

"""**apply the standard scalling on the columns 'Annual_Income', 'Monthly_Expenses','Total_Existing_Loan_Amount', 'Outstanding_Debt', 'Loan_Amount_Requested'**"""

#from sklearn.preprocessing import StandardScaler
#sc = StandardScaler()
#df['Annual_Income'] = sc.fit_transform(df[['Annual_Income']])
#df['Monthly_Expenses'] = sc.fit_transform(df[['Monthly_Expenses']])
#df['Total_Existing_Loan_Amount'] = sc.fit_transform(df[['Total_Existing_Loan_Amount']])
#df['Outstanding_Debt'] = sc.fit_transform(df[['Outstanding_Debt']])
#df['Loan_Amount_Requested'] = sc.fit_transform(df[['Loan_Amount_Requested']])

#df.head(5)

# print only the categorial columns from dataset
categorical_col = df.select_dtypes(include=['object','category']).columns
print(categorical_col)

# Print the Categories of columns with fields
for col in categorical_col:
    print("=" *50)
    print(f"column name : {col}")
    print(df[col].unique())

"""**encode the Ordinal categorical column Education['High School','Graduate',  'Postgraduate'] by OrdinalEncoder because we need encoding in order**"""

from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories = [['High School','Graduate', 'Postgraduate']])
df['Education'] = oe.fit_transform(df[['Education']])

df['Education'] = df['Education'].astype('int64')

df['Education'].head(5)

df.head(3)

"""**Split the Data**"""

# Assign features columns and Target Column
X = df.drop(columns=['Loan_Approval_Status'])
y = df['Loan_Approval_Status']
print(X.shape)
print(y.shape)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)

X_train.head(3)

y_train.head(3)

"""#**Encode the Nominal Categorical Columns by OneHotEncoding**

**What is Nominal Category ? There is no relationship between Categories**

**Why OneHotEncoding ?  It make new columns on the bases of categories in each column**

##**Encode X_Train**
"""

X_train.info()

X_train.shape

X_train.head(3)

# divide the X_train Dta into 2 parts 1-int,float  2-categorical
X_train_int_float_col = X_train.select_dtypes(include=['int64','float64']).columns
print(X_train_int_float_col)

X_train_categorical_col = X_train.select_dtypes(include=['object','category']).columns
print(X_train_categorical_col)

total_col = len(X_train_int_float_col) + len(X_train_categorical_col)
print("Total no of Columns : ", total_col)
print("Actual X_train Total no of columns : ", len(X_train.columns))

X_train_int_float_col.shape

X_train_categorical_col.shape

from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first',dtype=np.int32)

X_train_encoded_categorical_col = ohe.fit_transform(
    X_train[X_train_categorical_col]).toarray()
print(X_train_encoded_categorical_col)

X_train[X_train_int_float_col].values

"""**X_train >> join encoded categorical columns with int_float type columns**"""

np.hstack((X_train[X_train_int_float_col].values, X_train_encoded_categorical_col))

X_train_final = np.hstack((X_train[X_train_int_float_col].values, X_train_encoded_categorical_col))

X_train_final.shape

"""##**Encode X_Test**"""

X_test.info()

X_test.shape

X_test.head(3)

# divide the X_test Dta into 2 parts 1-int,float  2-categorical
X_test_int_float_col = X_test.select_dtypes(include=['int64','float64']).columns
print(X_test_int_float_col)

X_test_categorical_col = X_test.select_dtypes(include=['object','category']).columns
print(X_test_categorical_col)

total_col = len(X_test_int_float_col) + len(X_test_categorical_col)
print("Total no of Columns : ", total_col)
print("Actual X_test Total no of columns : ", len(X_test.columns))

X_test_int_float_col.shape

X_test_categorical_col.shape

X_test_encoded_categorical_col = ohe.fit_transform(
    X_test[X_test_categorical_col]).toarray()
print(X_test_encoded_categorical_col)

X_test[X_test_int_float_col].values

"""**X_test >> join encoded categorical columns with int_float type columns**"""

np.hstack((X_test[X_test_int_float_col].values, X_test_encoded_categorical_col))

X_test_final = np.hstack((X_test[X_test_int_float_col].values, X_test_encoded_categorical_col))

X_test_final.shape

"""**Create & Fit the Model Using Decision Tree Algorithm**"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

model = DecisionTreeClassifier(max_leaf_nodes=10,random_state=0)
model.fit(X_train_final, y_train)

"""**Predicting values on test set of data**"""

predicted_values = model.predict(X_test_final)

"""**Checking Test Accuracy**"""

print("Accuracy Score" , accuracy_score(y_test, predicted_values))
print("Precision Score" , precision_score(y_test, predicted_values, average='micro'))
print("Recall Score" , recall_score(y_test, predicted_values, average='micro'))
print("F1 Score" , f1_score(y_test, predicted_values,average='micro'))

# try to Train the model on different algorithms
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier as LightGBM

# initialize the algorithms
lr = LogisticRegression(solver='liblinear', penalty='l1')
svc = SVC(kernel = 'sigmoid', gamma=1.0)
linear_svc = LinearSVC(random_state=0, tol=1e-5)
dtc = DecisionTreeClassifier(max_depth=5)
rfc = RandomForestClassifier(n_estimators=50, random_state=2)
gbc = GradientBoostingClassifier(n_estimators=50, random_state=2)
etc = ExtraTreesClassifier(n_estimators=50, random_state=2)
xgb = XGBClassifier(n_estimators=50, random_state=2)
lgbm = LightGBM(n_estimators=50, random_state=2)

# make classifiers dictionary
classifiers = {
    'LogisticRegression'         : lr,
    'SVC'                        : svc,
    'LinearSVC'                  : linear_svc,
    'DecisionTreeClassifier'     : dtc,
    'RandomForestClassifier'     : rfc,
    'GradientBoostingClassifier' : gbc,
    'ExtraTreesClassifier'       : etc,
    'XGBClassifier'              : xgb,
    'LightGBM'                   : lgbm
    }

# make a function that predict train data and test data and find sccuracy score and precision for all selected algorithms
def train_classifier_f(clf, X_train_final, y_train, X_test_final, y_test):
    clf.fit(X_train_final, y_train)
    y_pred = clf.predict(X_test_final)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    return accuracy, precision, recall, f1

accuracy_scores = []
precision_scores = []
recall_scores = []
f1_scores = []

for name, clf in classifiers.items():
        current_accuracy, current_precision, current_recall, current_f1 = train_classifier_f(clf, X_train_final,y_train, X_test_final, y_test)

        print("For" , name)
        print("Accuracy" , current_accuracy)
        print("Precision" , current_precision)
        print("Recall" , current_recall)
        print("F1" , current_f1)

        accuracy_scores.append(current_accuracy)
        precision_scores.append(current_precision)
        recall_scores.append(current_recall)
        f1_scores.append(current_f1)

# make data frame for accuracy score and precision
performance_df = pd.DataFrame({'Algorithm':classifiers.keys(),
                             'Accuracy':accuracy_scores,
                             'Precision':precision_scores,
                             'Recall':recall_scores,
                             'F1':f1_scores}).sort_values('F1',ascending=False)
performance_df = performance_df.set_index('Algorithm')
performance_df.head(12)

"""###**Prefer f1-score because it balances precision and recall, helping reduce both wrong loan approvals and wrong loan rejections.**

###**I select LightGBM on the bases of f1 score**

**To Save the Model**
"""

import joblib
joblib.dump(lgbm, "/content/drive/MyDrive/LoanApprovalModel/LoanAapprovalTrainedModel.joblib")

joblib.dump(ohe, "/content/drive/MyDrive/LoanApprovalModel/onehotencoder.joblib")

joblib.dump(oe, "/content/drive/MyDrive/LoanApprovalModel/ordinalencoder.joblib")